### ISSUE TITLE
Trident thrown onto MyWorlds Nether portal still get teleported into the Nether

### ISSUE THREAD

**Issue by nhanledev** [JEFF-Media-GbR/BetterTridents#4]
Hello,

I am using MyWorlds plugin (https://www.spigotmc.org/resources/myworlds.39594/) as an alternative solution of Multiverse to create and manage multiple worlds.

I just discovered BetterTridents today, and have issue with throwing trident through Nether Portal.

The trident sometime get stuck on the portal and get teleported into the Nether.

My config:
```
void-saving: true
bedrock-impaling: false
bedrock-drop-chance: false
return-to-offhand: true
disable-loyalty-portals: true
check-for-updates: false
update-check-interval: 4
debug: true
```

Debug log at that moment:
```
[21:58:42 WARN]: [BetterTridents] [DEBUG] Trident throw Listener: ProjectileLaunchEvent
[21:58:42 WARN]: [BetterTridents] [DEBUG] Applying impaling level 0
[21:58:42 WARN]: [BetterTridents] [DEBUG] VoidListener
[21:58:42 WARN]: [BetterTridents] [DEBUG] New task: WatchTrident
```

**Comment by mfnalex** [comment]
Hi, all I can see from the meanwhile deleted video is a trident was thrown, then hit a wall in the nether? I am not sure what you mean, I mean obviously it'll stop when it hits a wall

**Comment by nhanledev** [comment]
> Hi, all I can see from the meanwhile deleted video is a trident was thrown, then hit a wall in the nether? I am not sure what you mean, I mean obviously it'll stop when it hits a wall.

Hello, I delete the video because it does not show clearly how the trident works in my case.
I threw it to the nether portal, and it still got teleported into the Nether. I have to go there to get it back.

**Comment by mfnalex** [comment]
oh I am stupid, I totally misunderstood this issue lol. You want to PREVENT loyalty tridents from entering the portal, I get it now. I'll look into this

**Comment by nhanledev** [comment]
> oh I am stupid, I totally misunderstood this issue lol. You want to PREVENT loyalty tridents from entering the portal, I get it now. I'll look into this

OMG I just realize that I forgot to mention about loyalty trident. I'm sorry and thank you <3

**Comment by Cazcez** [comment]
Hey, problem was actually on MyWorlds side and they fixed the issue on latest dev version [which you can download from here ](https://ci.mg-dev.eu/job/MyWorlds/) but I noticed there was another problem prevents disable-loyalty-portals option to work properly and it's fixed [on my PR](https://github.com/JEFF-Media-GbR/BetterTridents/pull/6). If you want, you can wait for Alex to merge my PR and upload to Spigot or you can build the BetterTridents from my fork with maven. Unfortunately Alex is having a rough time for a while and i don't think he will review and merge the PR soon. So waiting Alex can take few days or 2 or 3 weeks.

**Comment by nhanledev** [comment]
Hello, thank you for taking your time to inspect and work on this issue. I will build your BetterTrident's PR and use the snapshot version of MyWorlds to check if I need anything else. Have a nice day.

**Comment by nhanledev** [comment]
The combination of MyWorlds-1.19.3-v4-SNAPSHOT-215 and the build version from Cazcez's PR fix this issue.
DEBUG:
```
[18:57:58 WARN]: [BetterTridents] [DEBUG] VoidListener
[18:57:58 WARN]: [BetterTridents] [DEBUG] New task: WatchTrident
[18:57:58 WARN]: [BetterTridents] [DEBUG] Trident throw Listener: ProjectileLaunchEvent
[18:57:58 WARN]: [BetterTridents] [DEBUG] Applying impaling level 0
[18:57:59 WARN]: [BetterTridents] [DEBUG] Prevented loyalty trident from travelling through portal
[18:57:59 WARN]: [BetterTridents] [DEBUG] Prevented loyalty trident from travelling through portal
```

**Comment by Cazcez** [comment]
Nice to hear my PR fixes your problem. I hope Alex will merge my PR soon ^^

**Comment by mfnalex** [comment]
Updated version will be uploaded today - if I forget, nag me pls @Cazcez

**Comment by Cazcez** [comment]
NAG NAG

**Comment by Cazcez** [comment]
Nag nag

**Comment by Cazcez** [comment]
https://www.spigotmc.org/resources/replant.92668/update?update=495154
